version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.10
    steps:
    - checkout
    - run:
        command: npm install
    - run:
        command: npm test
workflows:
  version: 2
  workflow:
    jobs:
    - build
